/* AUTO-GENERATED by scripts/generate-manifest.ts — DO NOT EDIT. */
import { DRILLS_SCHEMA, EXAM_SCHEMA, FRONTMATTER_SCHEMA, LESSON_TEST_SCHEMA } from "@/lib/schema";
import type { Drill, ExamRecord, LessonMeta } from "@/lib/types";
import type { Element, MDXProps } from "mdx/types";

type MDXComp = (props: MDXProps) => Element;

import U0_L01Lesson, { frontmatter as U0_L01Fm } from "./units/u0/l01/lesson.mdx";
import U0_L01Lab from "./units/u0/l01/lab.md";
import U0_L01Test from "./units/u0/l01/test.json";
import U0_L02Lesson, { frontmatter as U0_L02Fm } from "./units/u0/l02/lesson.mdx";
import U0_L02Lab from "./units/u0/l02/lab.md";
import U0_L02Test from "./units/u0/l02/test.json";
import U0_L03Lesson, { frontmatter as U0_L03Fm } from "./units/u0/l03/lesson.mdx";
import U0_L03Lab from "./units/u0/l03/lab.md";
import U0_L03Test from "./units/u0/l03/test.json";
import U0_L04Lesson, { frontmatter as U0_L04Fm } from "./units/u0/l04/lesson.mdx";
import U0_L04Lab from "./units/u0/l04/lab.md";
import U0_L04Test from "./units/u0/l04/test.json";
import U0_L05Lesson, { frontmatter as U0_L05Fm } from "./units/u0/l05/lesson.mdx";
import U0_L05Lab from "./units/u0/l05/lab.md";
import U0_L05Test from "./units/u0/l05/test.json";
import U0_L06Lesson, { frontmatter as U0_L06Fm } from "./units/u0/l06/lesson.mdx";
import U0_L06Lab from "./units/u0/l06/lab.md";
import U0_L06Test from "./units/u0/l06/test.json";
import U0_L07Lesson, { frontmatter as U0_L07Fm } from "./units/u0/l07/lesson.mdx";
import U0_L07Lab from "./units/u0/l07/lab.md";
import U0_L07Test from "./units/u0/l07/test.json";
import U0_L08Lesson, { frontmatter as U0_L08Fm } from "./units/u0/l08/lesson.mdx";
import U0_L08Lab from "./units/u0/l08/lab.md";
import U0_L08Test from "./units/u0/l08/test.json";
import U0_L09Lesson, { frontmatter as U0_L09Fm } from "./units/u0/l09/lesson.mdx";
import U0_L09Lab from "./units/u0/l09/lab.md";
import U0_L09Test from "./units/u0/l09/test.json";
import U0_L10Lesson, { frontmatter as U0_L10Fm } from "./units/u0/l10/lesson.mdx";
import U0_L10Lab from "./units/u0/l10/lab.md";
import U0_L10Test from "./units/u0/l10/test.json";
import U0_L11Lesson, { frontmatter as U0_L11Fm } from "./units/u0/l11/lesson.mdx";
import U0_L11Lab from "./units/u0/l11/lab.md";
import U0_L11Test from "./units/u0/l11/test.json";
import U0_L12Lesson, { frontmatter as U0_L12Fm } from "./units/u0/l12/lesson.mdx";
import U0_L12Lab from "./units/u0/l12/lab.md";
import U0_L12Test from "./units/u0/l12/test.json";
import U0_L13Lesson, { frontmatter as U0_L13Fm } from "./units/u0/l13/lesson.mdx";
import U0_L13Lab from "./units/u0/l13/lab.md";
import U0_L13Test from "./units/u0/l13/test.json";
import U0_L14Lesson, { frontmatter as U0_L14Fm } from "./units/u0/l14/lesson.mdx";
import U0_L14Lab from "./units/u0/l14/lab.md";
import U0_L14Test from "./units/u0/l14/test.json";
import U0_L15Lesson, { frontmatter as U0_L15Fm } from "./units/u0/l15/lesson.mdx";
import U0_L15Lab from "./units/u0/l15/lab.md";
import U0_L15Test from "./units/u0/l15/test.json";
import U1_L01Lesson, { frontmatter as U1_L01Fm } from "./units/u1/l01/lesson.mdx";
import U1_L01Lab from "./units/u1/l01/lab.md";
import U1_L01Test from "./units/u1/l01/test.json";
import U1_L02Lesson, { frontmatter as U1_L02Fm } from "./units/u1/l02/lesson.mdx";
import U1_L02Lab from "./units/u1/l02/lab.md";
import U1_L02Test from "./units/u1/l02/test.json";
import U1_L03Lesson, { frontmatter as U1_L03Fm } from "./units/u1/l03/lesson.mdx";
import U1_L03Lab from "./units/u1/l03/lab.md";
import U1_L03Test from "./units/u1/l03/test.json";
import U1_L04Lesson, { frontmatter as U1_L04Fm } from "./units/u1/l04/lesson.mdx";
import U1_L04Lab from "./units/u1/l04/lab.md";
import U1_L04Test from "./units/u1/l04/test.json";
import U1_L05Lesson, { frontmatter as U1_L05Fm } from "./units/u1/l05/lesson.mdx";
import U1_L05Lab from "./units/u1/l05/lab.md";
import U1_L05Test from "./units/u1/l05/test.json";
import U1_L06Lesson, { frontmatter as U1_L06Fm } from "./units/u1/l06/lesson.mdx";
import U1_L06Lab from "./units/u1/l06/lab.md";
import U1_L06Test from "./units/u1/l06/test.json";
import U1_L07Lesson, { frontmatter as U1_L07Fm } from "./units/u1/l07/lesson.mdx";
import U1_L07Lab from "./units/u1/l07/lab.md";
import U1_L07Test from "./units/u1/l07/test.json";
import U1_L08Lesson, { frontmatter as U1_L08Fm } from "./units/u1/l08/lesson.mdx";
import U1_L08Lab from "./units/u1/l08/lab.md";
import U1_L08Test from "./units/u1/l08/test.json";
import U1_L09Lesson, { frontmatter as U1_L09Fm } from "./units/u1/l09/lesson.mdx";
import U1_L09Lab from "./units/u1/l09/lab.md";
import U1_L09Test from "./units/u1/l09/test.json";
import U1_L10Lesson, { frontmatter as U1_L10Fm } from "./units/u1/l10/lesson.mdx";
import U1_L10Lab from "./units/u1/l10/lab.md";
import U1_L10Test from "./units/u1/l10/test.json";
import U1_L11Lesson, { frontmatter as U1_L11Fm } from "./units/u1/l11/lesson.mdx";
import U1_L11Lab from "./units/u1/l11/lab.md";
import U1_L11Test from "./units/u1/l11/test.json";
import U2_L01Lesson, { frontmatter as U2_L01Fm } from "./units/u2/l01/lesson.mdx";
import U2_L01Lab from "./units/u2/l01/lab.md";
import U2_L01Test from "./units/u2/l01/test.json";
import U2_L02Lesson, { frontmatter as U2_L02Fm } from "./units/u2/l02/lesson.mdx";
import U2_L02Lab from "./units/u2/l02/lab.md";
import U2_L02Test from "./units/u2/l02/test.json";
import U2_L03Lesson, { frontmatter as U2_L03Fm } from "./units/u2/l03/lesson.mdx";
import U2_L03Lab from "./units/u2/l03/lab.md";
import U2_L03Test from "./units/u2/l03/test.json";
import U2_L04Lesson, { frontmatter as U2_L04Fm } from "./units/u2/l04/lesson.mdx";
import U2_L04Lab from "./units/u2/l04/lab.md";
import U2_L04Test from "./units/u2/l04/test.json";
import U2_L05Lesson, { frontmatter as U2_L05Fm } from "./units/u2/l05/lesson.mdx";
import U2_L05Lab from "./units/u2/l05/lab.md";
import U2_L05Test from "./units/u2/l05/test.json";
import U2_L06Lesson, { frontmatter as U2_L06Fm } from "./units/u2/l06/lesson.mdx";
import U2_L06Lab from "./units/u2/l06/lab.md";
import U2_L06Test from "./units/u2/l06/test.json";
import U2_L07Lesson, { frontmatter as U2_L07Fm } from "./units/u2/l07/lesson.mdx";
import U2_L07Lab from "./units/u2/l07/lab.md";
import U2_L07Test from "./units/u2/l07/test.json";
import U2_L08Lesson, { frontmatter as U2_L08Fm } from "./units/u2/l08/lesson.mdx";
import U2_L08Lab from "./units/u2/l08/lab.md";
import U2_L08Test from "./units/u2/l08/test.json";
import U2_L09Lesson, { frontmatter as U2_L09Fm } from "./units/u2/l09/lesson.mdx";
import U2_L09Lab from "./units/u2/l09/lab.md";
import U2_L09Test from "./units/u2/l09/test.json";
import U2_L10Lesson, { frontmatter as U2_L10Fm } from "./units/u2/l10/lesson.mdx";
import U2_L10Lab from "./units/u2/l10/lab.md";
import U2_L10Test from "./units/u2/l10/test.json";
import U3_L01Lesson, { frontmatter as U3_L01Fm } from "./units/u3/l01/lesson.mdx";
import U3_L01Lab from "./units/u3/l01/lab.md";
import U3_L01Test from "./units/u3/l01/test.json";
import U3_L02Lesson, { frontmatter as U3_L02Fm } from "./units/u3/l02/lesson.mdx";
import U3_L02Lab from "./units/u3/l02/lab.md";
import U3_L02Test from "./units/u3/l02/test.json";
import U3_L03Lesson, { frontmatter as U3_L03Fm } from "./units/u3/l03/lesson.mdx";
import U3_L03Lab from "./units/u3/l03/lab.md";
import U3_L03Test from "./units/u3/l03/test.json";
import U3_L04Lesson, { frontmatter as U3_L04Fm } from "./units/u3/l04/lesson.mdx";
import U3_L04Lab from "./units/u3/l04/lab.md";
import U3_L04Test from "./units/u3/l04/test.json";
import U3_L05Lesson, { frontmatter as U3_L05Fm } from "./units/u3/l05/lesson.mdx";
import U3_L05Lab from "./units/u3/l05/lab.md";
import U3_L05Test from "./units/u3/l05/test.json";
import U3_L06Lesson, { frontmatter as U3_L06Fm } from "./units/u3/l06/lesson.mdx";
import U3_L06Lab from "./units/u3/l06/lab.md";
import U3_L06Test from "./units/u3/l06/test.json";
import U3_L07Lesson, { frontmatter as U3_L07Fm } from "./units/u3/l07/lesson.mdx";
import U3_L07Lab from "./units/u3/l07/lab.md";
import U3_L07Test from "./units/u3/l07/test.json";
import U3_L08Lesson, { frontmatter as U3_L08Fm } from "./units/u3/l08/lesson.mdx";
import U3_L08Lab from "./units/u3/l08/lab.md";
import U3_L08Test from "./units/u3/l08/test.json";
import U3_L09Lesson, { frontmatter as U3_L09Fm } from "./units/u3/l09/lesson.mdx";
import U3_L09Lab from "./units/u3/l09/lab.md";
import U3_L09Test from "./units/u3/l09/test.json";
import U3_L10Lesson, { frontmatter as U3_L10Fm } from "./units/u3/l10/lesson.mdx";
import U3_L10Lab from "./units/u3/l10/lab.md";
import U3_L10Test from "./units/u3/l10/test.json";

import exams_u0_jsonJson from "./exams/u0.json";
import exams_u1_jsonJson from "./exams/u1.json";
import exams_u2_jsonJson from "./exams/u2.json";
import exams_u3_jsonJson from "./exams/u3.json";
import drillsJson from "./drills.json";

const lessonDefs = [
  { Lesson: U0_L01Lesson, Lab: U0_L01Lab, testJson: U0_L01Test, fm: U0_L01Fm } as const,
  { Lesson: U0_L02Lesson, Lab: U0_L02Lab, testJson: U0_L02Test, fm: U0_L02Fm } as const,
  { Lesson: U0_L03Lesson, Lab: U0_L03Lab, testJson: U0_L03Test, fm: U0_L03Fm } as const,
  { Lesson: U0_L04Lesson, Lab: U0_L04Lab, testJson: U0_L04Test, fm: U0_L04Fm } as const,
  { Lesson: U0_L05Lesson, Lab: U0_L05Lab, testJson: U0_L05Test, fm: U0_L05Fm } as const,
  { Lesson: U0_L06Lesson, Lab: U0_L06Lab, testJson: U0_L06Test, fm: U0_L06Fm } as const,
  { Lesson: U0_L07Lesson, Lab: U0_L07Lab, testJson: U0_L07Test, fm: U0_L07Fm } as const,
  { Lesson: U0_L08Lesson, Lab: U0_L08Lab, testJson: U0_L08Test, fm: U0_L08Fm } as const,
  { Lesson: U0_L09Lesson, Lab: U0_L09Lab, testJson: U0_L09Test, fm: U0_L09Fm } as const,
  { Lesson: U0_L10Lesson, Lab: U0_L10Lab, testJson: U0_L10Test, fm: U0_L10Fm } as const,
  { Lesson: U0_L11Lesson, Lab: U0_L11Lab, testJson: U0_L11Test, fm: U0_L11Fm } as const,
  { Lesson: U0_L12Lesson, Lab: U0_L12Lab, testJson: U0_L12Test, fm: U0_L12Fm } as const,
  { Lesson: U0_L13Lesson, Lab: U0_L13Lab, testJson: U0_L13Test, fm: U0_L13Fm } as const,
  { Lesson: U0_L14Lesson, Lab: U0_L14Lab, testJson: U0_L14Test, fm: U0_L14Fm } as const,
  { Lesson: U0_L15Lesson, Lab: U0_L15Lab, testJson: U0_L15Test, fm: U0_L15Fm } as const,
  { Lesson: U1_L01Lesson, Lab: U1_L01Lab, testJson: U1_L01Test, fm: U1_L01Fm } as const,
  { Lesson: U1_L02Lesson, Lab: U1_L02Lab, testJson: U1_L02Test, fm: U1_L02Fm } as const,
  { Lesson: U1_L03Lesson, Lab: U1_L03Lab, testJson: U1_L03Test, fm: U1_L03Fm } as const,
  { Lesson: U1_L04Lesson, Lab: U1_L04Lab, testJson: U1_L04Test, fm: U1_L04Fm } as const,
  { Lesson: U1_L05Lesson, Lab: U1_L05Lab, testJson: U1_L05Test, fm: U1_L05Fm } as const,
  { Lesson: U1_L06Lesson, Lab: U1_L06Lab, testJson: U1_L06Test, fm: U1_L06Fm } as const,
  { Lesson: U1_L07Lesson, Lab: U1_L07Lab, testJson: U1_L07Test, fm: U1_L07Fm } as const,
  { Lesson: U1_L08Lesson, Lab: U1_L08Lab, testJson: U1_L08Test, fm: U1_L08Fm } as const,
  { Lesson: U1_L09Lesson, Lab: U1_L09Lab, testJson: U1_L09Test, fm: U1_L09Fm } as const,
  { Lesson: U1_L10Lesson, Lab: U1_L10Lab, testJson: U1_L10Test, fm: U1_L10Fm } as const,
  { Lesson: U1_L11Lesson, Lab: U1_L11Lab, testJson: U1_L11Test, fm: U1_L11Fm } as const,
  { Lesson: U2_L01Lesson, Lab: U2_L01Lab, testJson: U2_L01Test, fm: U2_L01Fm } as const,
  { Lesson: U2_L02Lesson, Lab: U2_L02Lab, testJson: U2_L02Test, fm: U2_L02Fm } as const,
  { Lesson: U2_L03Lesson, Lab: U2_L03Lab, testJson: U2_L03Test, fm: U2_L03Fm } as const,
  { Lesson: U2_L04Lesson, Lab: U2_L04Lab, testJson: U2_L04Test, fm: U2_L04Fm } as const,
  { Lesson: U2_L05Lesson, Lab: U2_L05Lab, testJson: U2_L05Test, fm: U2_L05Fm } as const,
  { Lesson: U2_L06Lesson, Lab: U2_L06Lab, testJson: U2_L06Test, fm: U2_L06Fm } as const,
  { Lesson: U2_L07Lesson, Lab: U2_L07Lab, testJson: U2_L07Test, fm: U2_L07Fm } as const,
  { Lesson: U2_L08Lesson, Lab: U2_L08Lab, testJson: U2_L08Test, fm: U2_L08Fm } as const,
  { Lesson: U2_L09Lesson, Lab: U2_L09Lab, testJson: U2_L09Test, fm: U2_L09Fm } as const,
  { Lesson: U2_L10Lesson, Lab: U2_L10Lab, testJson: U2_L10Test, fm: U2_L10Fm } as const,
  { Lesson: U3_L01Lesson, Lab: U3_L01Lab, testJson: U3_L01Test, fm: U3_L01Fm } as const,
  { Lesson: U3_L02Lesson, Lab: U3_L02Lab, testJson: U3_L02Test, fm: U3_L02Fm } as const,
  { Lesson: U3_L03Lesson, Lab: U3_L03Lab, testJson: U3_L03Test, fm: U3_L03Fm } as const,
  { Lesson: U3_L04Lesson, Lab: U3_L04Lab, testJson: U3_L04Test, fm: U3_L04Fm } as const,
  { Lesson: U3_L05Lesson, Lab: U3_L05Lab, testJson: U3_L05Test, fm: U3_L05Fm } as const,
  { Lesson: U3_L06Lesson, Lab: U3_L06Lab, testJson: U3_L06Test, fm: U3_L06Fm } as const,
  { Lesson: U3_L07Lesson, Lab: U3_L07Lab, testJson: U3_L07Test, fm: U3_L07Fm } as const,
  { Lesson: U3_L08Lesson, Lab: U3_L08Lab, testJson: U3_L08Test, fm: U3_L08Fm } as const,
  { Lesson: U3_L09Lesson, Lab: U3_L09Lab, testJson: U3_L09Test, fm: U3_L09Fm } as const,
  { Lesson: U3_L10Lesson, Lab: U3_L10Lab, testJson: U3_L10Test, fm: U3_L10Fm } as const,
];

export interface LessonRecord extends LessonMeta {
  Lesson: MDXComp;
  Lab: MDXComp;
}

export const lessons: LessonRecord[] = lessonDefs.map((d) => {
  const fm = FRONTMATTER_SCHEMA.parse(d.fm);
  const test = LESSON_TEST_SCHEMA.parse(d.testJson);
  return {
    id: fm.id,
    slug: fm.slug,
    unitIndex: fm.unit,
    unitSlug: fm.unitSlug,
    order: fm.order,
    title: fm.title,
    topics: [...fm.topics],
    cites: [...fm.cites],
    durationMin: fm.durationMin,
    Lesson: d.Lesson,
    Lab: d.Lab,
    test,
  };
});

const ids = new Set<string>();
const slugs = new Set<string>();
for (const l of lessons) {
  if (ids.has(l.id)) throw new Error(`duplicate lesson id: ${l.id}`);
  ids.add(l.id);
  if (slugs.has(`${l.unitSlug}/${l.slug}`)) throw new Error(`duplicate lesson slug: ${l.unitSlug}/${l.slug}`);
  slugs.add(`${l.unitSlug}/${l.slug}`);
}

export const UNITS = [
  { index: 0, slug: "rust-core", title: "Rust for Goose", tagline: "From JS/TS to reading the goose codebase like a maintainer." } as const,
  { index: 1, slug: "architecture", title: "Architecture Mastery", tagline: "Navigate, trace, and explain any subsystem." } as const,
  { index: 2, slug: "core-contribution", title: "Core Contribution", tagline: "Land real core-lib PRs the way a maintainer would." } as const,
  { index: 3, slug: "extensions", title: "Extension Mastery", tagline: "Ship production-grade providers, MCP tools, and plugins." } as const,
];

export const unitLessonCount: Record<string, number> = Object.fromEntries(
  UNITS.map((u) => [u.slug, lessons.filter((l) => l.unitSlug === u.slug).length])
);

export function lessonById(id: string): LessonRecord | undefined {
  return lessons.find((l) => l.id === id);
}

export function lessonsForUnit(unitSlug: string): LessonRecord[] {
  return lessons.filter((l) => l.unitSlug === unitSlug).sort((a, b) => a.order - b.order);
}

export function lessonByRoute(unitSlug: string, lessonSlug: string): LessonRecord | undefined {
  return lessons.find((l) => l.unitSlug === unitSlug && l.slug === lessonSlug);
}

export const topicIndex: Record<string, LessonMeta[]> = {};
for (const l of lessons) {
  for (const t of l.topics) {
    (topicIndex[t] ??= []).push({
      id: l.id,
      slug: l.slug,
      unitIndex: l.unitIndex,
      unitSlug: l.unitSlug,
      order: l.order,
      title: l.title,
      topics: l.topics,
      cites: l.cites,
      durationMin: l.durationMin,
    });
  }
}

export const exams: ExamRecord[] = [
  EXAM_SCHEMA.parse(exams_u0_jsonJson),
  EXAM_SCHEMA.parse(exams_u1_jsonJson),
  EXAM_SCHEMA.parse(exams_u2_jsonJson),
  EXAM_SCHEMA.parse(exams_u3_jsonJson),
];

export const drills: Drill[] = DRILLS_SCHEMA.parse(drillsJson);

