import fs from "node:fs";
import path from "node:path";
import { parseFrontmatterRaw } from "../lib/fmparse";
import { FRONTMATTER_SCHEMA } from "../lib/schema";
import { lessonDirs } from "../lib/content-io";

const CONTENT_ROOT = path.resolve(__dirname, "..", "content");
const OUT_FILE = path.join(CONTENT_ROOT, "manifest.ts");

const UNITS = [
  { index: 0, slug: "rust-core", title: "Rust for Goose", tagline: "From JS/TS to reading the goose codebase like a maintainer." },
  { index: 1, slug: "architecture", title: "Architecture Mastery", tagline: "Navigate, trace, and explain any subsystem." },
  { index: 2, slug: "core-contribution", title: "Core Contribution", tagline: "Land real core-lib PRs the way a maintainer would." },
  { index: 3, slug: "extensions", title: "Extension Mastery", tagline: "Ship production-grade providers, MCP tools, and plugins." },
];

function ident(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, "_");
}

export function generateManifest(): string {
  const lessons = lessonDirs(CONTENT_ROOT)
    .map((dir) => {
      const rel = path.relative(CONTENT_ROOT, dir).split(path.sep).join("/");
      const [, unitPart, lessonPart] = rel.split("/");
      const unitNumber = Number(unitPart.slice(1));
      const fm = FRONTMATTER_SCHEMA.parse(
        parseFrontmatterRaw(fs.readFileSync(path.join(dir, "lesson.mdx"), "utf8"))?.data
      );
      return {
        rel,
        unitNumber,
        id: fm.id,
        order: fm.order,
        varPrefix: `${ident(unitPart).toUpperCase()}_${ident(lessonPart).toUpperCase()}`,
      };
    })
    .sort((a, b) => a.unitNumber - b.unitNumber || a.order - b.order);

  const exams = ["u0", "u1", "u2", "u3"].map((u) => `exams/${u}.json`);

  const lines: string[] = [];
  lines.push("/* AUTO-GENERATED by scripts/generate-manifest.ts — DO NOT EDIT. */");
  lines.push('import { DRILLS_SCHEMA, EXAM_SCHEMA, FRONTMATTER_SCHEMA, LESSON_TEST_SCHEMA } from "@/lib/schema";');
  lines.push('import type { Drill, ExamRecord, LessonMeta, TestItem } from "@/lib/types";');
  lines.push('import type { Element, MDXProps } from "mdx/types";');
  lines.push("");
  lines.push("type MDXComp = (props: MDXProps) => Element;");
  lines.push("");

  for (const l of lessons) {
    lines.push(`import ${l.varPrefix}Lesson, { frontmatter as ${l.varPrefix}Fm } from "./${l.rel}/lesson.mdx";`);
    lines.push(`import ${l.varPrefix}Lab from "./${l.rel}/lab.md";`);
    lines.push(`import ${l.varPrefix}Test from "./${l.rel}/test.json";`);
  }
  lines.push("");
  for (const e of exams) {
    lines.push(`import ${ident(e)}Json from "./${e}";`);
  }
  lines.push('import drillsJson from "./drills.json";');
  lines.push("");
  lines.push("const lessonDefs = [");
  for (const l of lessons) {
    lines.push(
      `  { Lesson: ${l.varPrefix}Lesson, Lab: ${l.varPrefix}Lab, testJson: ${l.varPrefix}Test, fm: ${l.varPrefix}Fm } as const,`
    );
  }
  lines.push("];");
  lines.push("");
  lines.push("export interface LessonRecord extends LessonMeta {");
  lines.push("  Lesson: MDXComp;");
  lines.push("  Lab: MDXComp;");
  lines.push("  test: TestItem[];");
  lines.push("}");
  lines.push("");
  lines.push("export const lessons: LessonRecord[] = lessonDefs.map((d) => {");
  lines.push("  const fm = FRONTMATTER_SCHEMA.parse(d.fm);");
  lines.push("  const test = LESSON_TEST_SCHEMA.parse(d.testJson);");
  lines.push("  return {");
  lines.push("    id: fm.id,");
  lines.push("    slug: fm.slug,");
  lines.push("    unitIndex: fm.unit,");
  lines.push("    unitSlug: fm.unitSlug,");
  lines.push("    order: fm.order,");
  lines.push("    title: fm.title,");
  lines.push("    topics: [...fm.topics],");
  lines.push("    cites: [...fm.cites],");
  lines.push("    durationMin: fm.durationMin,");
  lines.push("    Lesson: d.Lesson,");
  lines.push("    Lab: d.Lab,");
  lines.push("    test,");
  lines.push("  };");
  lines.push("});");
  lines.push("");
  lines.push("const ids = new Set<string>();");
  lines.push("const slugs = new Set<string>();");
  lines.push("for (const l of lessons) {");
  lines.push('  if (ids.has(l.id)) throw new Error(`duplicate lesson id: ${l.id}`);');
  lines.push("  ids.add(l.id);");
  lines.push('  if (slugs.has(`${l.unitSlug}/${l.slug}`)) throw new Error(`duplicate lesson slug: ${l.unitSlug}/${l.slug}`);');
  lines.push('  slugs.add(`${l.unitSlug}/${l.slug}`);');
  lines.push("}");
  lines.push("");
  lines.push("export const UNITS = [");
  for (const u of UNITS) {
    lines.push(
      `  { index: ${u.index}, slug: "${u.slug}", title: "${u.title}", tagline: ${JSON.stringify(u.tagline)} } as const,`
    );
  }
  lines.push("];");
  lines.push("");
  lines.push("export const unitLessonCount: Record<string, number> = Object.fromEntries(");
  lines.push('  UNITS.map((u) => [u.slug, lessons.filter((l) => l.unitSlug === u.slug).length])');
  lines.push(");");
  lines.push("");
  lines.push("export function lessonById(id: string): LessonRecord | undefined {");
  lines.push("  return lessons.find((l) => l.id === id);");
  lines.push("}");
  lines.push("");
  lines.push("export function lessonsForUnit(unitSlug: string): LessonRecord[] {");
  lines.push("  return lessons.filter((l) => l.unitSlug === unitSlug).sort((a, b) => a.order - b.order);");
  lines.push("}");
  lines.push("");
  lines.push("export function lessonByRoute(unitSlug: string, lessonSlug: string): LessonRecord | undefined {");
  lines.push("  return lessons.find((l) => l.unitSlug === unitSlug && l.slug === lessonSlug);");
  lines.push("}");
  lines.push("");
  lines.push("export const topicIndex: Record<string, LessonMeta[]> = {};");
  lines.push("for (const l of lessons) {");
  lines.push("  for (const t of l.topics) {");
  lines.push("    (topicIndex[t] ??= []).push({");
  lines.push("      id: l.id,");
  lines.push("      slug: l.slug,");
  lines.push("      unitIndex: l.unitIndex,");
  lines.push("      unitSlug: l.unitSlug,");
  lines.push("      order: l.order,");
  lines.push("      title: l.title,");
  lines.push("      topics: l.topics,");
  lines.push("      cites: l.cites,");
  lines.push("      durationMin: l.durationMin,");
  lines.push("    });");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  lines.push("export const exams: ExamRecord[] = [");
  for (const e of exams) {
    lines.push(`  EXAM_SCHEMA.parse(${ident(e)}Json),`);
  }
  lines.push("];");
  lines.push("");
  lines.push("export const drills: Drill[] = DRILLS_SCHEMA.parse(drillsJson);");
  lines.push("");
  return lines.join("\n") + "\n";
}

if (require.main === module) {
  const out = generateManifest();
  fs.writeFileSync(OUT_FILE, out, "utf8");
  console.log(`manifest written: ${path.relative(process.cwd(), OUT_FILE)} (${(out.length / 1024).toFixed(1)} KB)`);
}